import { FaShoppingCart } from "react-icons/fa";
export const FeaturedItems = [
  
  {
    id: 1,
    Company: "IndianGarrageCo",
    Itemname: "oversized",
    url: "/images/MensPageImg/OsBlue.png",
    price: 4525,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "men",
    rating: 3,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 2,
    Company: "IndianGarrageCo",
    Itemname: "oversized",
    url: "/images/MensPageImg/OsGrey.png",
    price: 1950,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "men",
    rating: 4,
    stock: "in",
    delivery: "slow",
  },
  {
    id: 3,
    Company: "IndianGarrageCo",
    Itemname: "footwear",
    url: "/images/MensPageImg/shoes2.png",
    price: 4555,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "footwear",
    rating: 3,
    stock: "out",
    delivery: "fast",
  },
  {
    id: 4,
    Company: "IndianGarrageCo",
    Itemname: "footwear",
    url: "/images/MensPageImg/shoes1.png",
    price: 1500,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "footwear",
    rating: 3,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 5,
    Company: "IndianGarrageCo",
    Itemname: "footwear",
    url: "/images/MensPageImg/shoes3.png",
    price: 1465,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "footwear",
    rating: 4,
    stock: "in",
    delivery: "slow",
  },
  {
    id: 6,
    Company: "IndianGarrageCo",
    Itemname: "short",
    url: "/images/MensPageImg/short1.png",
    price: 1000,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "men",
    rating: 5,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 7,
    Company: "IndianGarrageCo",
    Itemname: "short",
    url: "/images/MensPageImg/short2.png",
    price: 1600,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "men",
    rating: 5,
    stock: "out",
    delivery: "fast",
  },
  {
    id: 8,
    Company: "IndianGarrageCo",
    Itemname: "short",
    url: "/images/MensPageImg/short3.png",
    price: 1725,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "men",
    rating: 5,
    stock: "in",
    delivery: "slow",
  },

  {
    id: 9,
    Company: "IndianGarrageCo",
    Itemname: "jacket",
    url: "/images/WomenAssets/Wjacket1.png",
    price: 1525,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "women",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 10,
    Company: "IndianGarrageCo",
    Itemname: "Jacket",
    url: "/images/WomenAssets/Wjacket2.png",
    price: 1750,
    cart: <FaShoppingCart />,
    quantity: 1,

    type: "women",
    rating: 3,
    stock: "in",
    delivery: "standard",
  },
  {
    id: 11,
    Company: "IndianGarrageCo",
    Itemname: "Jacket",
    url: "/images/WomenAssets/Wjacket3.png",
    price: 1400,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "women",
    rating: 4,
    stock: "out",
    delivery: "fast",
  },
  {
    id: 12,
    Company: "IndianGarrageCo",
    Itemname: "jeans",
    url: "/images/WomenAssets/Wjeans1.png",
    price: 1325,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "women",
    rating: 3,
    stock: "in",
    delivery: "standard",
  },
  {
    id: 13,
    Company: "IndianGarrageCo",
    Itemname: "jeans",
    url: "/images/WomenAssets/Wjeans2.png",
    price: 1250,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "women",
    rating: 2,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 14,
    Company: "IndianGarrageCo",
    Itemname: "jeans",
    url: "/images/WomenAssets/Wjeans3.png",
    price: 1785,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "women",
    rating: 4,
    stock: "out",
    delivery: "standard",
  },
  {
    id: 15,
    Company: "IndianGarrageCo",
    Itemname: "casualShirt",
    url: "/images/MensPageImg/blackshirt.png",
    price: 2500,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "men",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 16,
    Company: "IndianGarrageCo",
    Itemname: "casualShirt",
    url: "/images/MensPageImg/blackdottedshirt.png",
    price: 3500,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "men",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 17,
    Company: "IndianGarrageCo",
    Itemname: "casualShirt",
    url: "/images/MensPageImg/floralShirt.png",
    price: 1500,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "men",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 18,
    Company: "IndianGarrageCo",
    Itemname: "cargo",
    url: "/images/MensPageImg/Cargo1.png",
    price: 500,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "men",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 19,
    Company: "IndianGarrageCo",
    Itemname: "cargo",
    url: "/images/MensPageImg/Cargo2.png",
    price: 4500,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "men",
    rating: 4,
    stock: "out",
    delivery: "fast",
  },
  {
    id: 20,
    Company: "IndianGarrageCo",
    Itemname: "cargo",
    url: "/images/MensPageImg/Cargo3.png",
    price: 1525,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "men",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 21,
    Company: "IndianGarrageCo",
    Itemname: "oversized",
    url: "/images/MensPageImg/OsBlack.png",
    price: 1700,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "men",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },

  {
    id: 22,
    Company: "IndianGarrageCo",
    Itemname: "plazo",
    url: "/images/WomenAssets/Wplazo1.png",
    price: 1585,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "women",
    rating: 4,
    stock: "out",
    delivery: "fast",
  },
  {
    id: 23,
    Company: "IndianGarrageCo",
    Itemname: "plazo ",
    url: "/images/WomenAssets/Wplazo2.png",
    price: 4444,
    cart: <FaShoppingCart />,

    quantity: 1,
    type: "women",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 24,
    Company: "IndianGarrageCo",
    Itemname: "plazo",
    url: "/images/WomenAssets/Wplazo3.png",
    price: 5005,
    cart: <FaShoppingCart />,
    quantity: 1,

    type: "women",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },

  {
    id: 25,
    Company: "IndianGarrageCo",
    Itemname: "skirt",
    url: "/images/WomenAssets/Wskirt1.png",
    price: 9500,
    cart: <FaShoppingCart />,
    quantity: 1,

    type: "women",
    rating: 4,
    stock: "out",
    delivery: "fast",
  },
  {
    id: 26,
    Company: "IndianGarrageCo",
    Itemname: "skirt",
    url: "/images/WomenAssets/Wskirt2.png",
    price: 4525,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "women",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 27,
    Company: "IndianGarrageCo",
    Itemname: "skirt",
    url: "/images/WomenAssets/Wskirt3.png",
    price: 1000,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "women",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 28,
    Company: "IndianGarrageCo",
    Itemname: "top",
    url: "/images/WomenAssets/Wtop1.png",
    price: 950,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "women",
    rating: 4,
    stock: "out",
    delivery: "fast",
  },
  {
    id: 29,
    Company: "IndianGarrageCo",
    Itemname: "top",
    url: "/images/WomenAssets/Wtop2.png",
    price: 1005,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "women",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 30,
    Company: "IndianGarrageCo",
    Itemname: "top",
    url: "/images/WomenAssets/Wtop3.png",
    price: 1250,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "women",
    rating: 4,
    stock: "out",
    delivery: "standard",
  },
];
