import { FaShoppingCart} from "react-icons/fa";
export const MenAssets = [
  {
    id: 1,
    Company: "IndianGarrageCo",
    Itemname: "casualShirt",
    url: "/images/MensPageImg/blackshirt.png",
    price: 2500,
    cart: <FaShoppingCart />,
    quantity:1,
  },
  {
    id: 2,
    Company: "IndianGarrageCo",
    Itemname: "casualShirt",
    url: "/images/MensPageImg/blackdottedshirt.png",
    price: 3500,
    cart: <FaShoppingCart />,
    quantity:1,
  },
  {
    id: 3,
    Company: "IndianGarrageCo",
    Itemname: "casualShirt",
    url: "/images/MensPageImg/floralShirt.png",
    price: 1500,
    cart: <FaShoppingCart />,
    quantity:1,
  },
  {
    id: 4,
    Company: "IndianGarrageCo",
    Itemname: "cargo",
    url: "/images/MensPageImg/Cargo1.png",
    price: 500,
    cart: <FaShoppingCart />,
    quantity:1,
  },
  {
    id: 5,
    Company: "IndianGarrageCo",
    Itemname: "cargo",
    url: "/images/MensPageImg/Cargo2.png",
    price: 4500,
    cart: <FaShoppingCart />,
    quantity:1,
  },
  {
    id: 6,
    Company: "IndianGarrageCo",
    Itemname: "cargo",
    url: "/images/MensPageImg/Cargo3.png",
    price: 1525,
    cart: <FaShoppingCart />,
    quantity:1,
  },
  {
    id: 7,
    Company: "IndianGarrageCo",
    Itemname: "oversized",
    url: "/images/MensPageImg/OsBlack.png",
    price: 1700,
    cart: <FaShoppingCart />,
    quantity:1,
  },
  {
    id: 8,
    Company: "IndianGarrageCo",
    Itemname: "oversized",
    url: "/images/MensPageImg/OsBlue.png",
    price: 4525,
    cart: <FaShoppingCart />,
    quantity:1,
  },
  {
    id: 9,
    Company: "IndianGarrageCo",
    Itemname: "oversized",
    url: "/images/MensPageImg/OsGrey.png",
    price: 1950,
    cart: <FaShoppingCart />,
    quantity:1,
  },
  {
    id: 10,
    Company: "IndianGarrageCo",
    Itemname: "footwear",
    url: "/images/MensPageImg/shoes2.png",
    price: 4555,
    cart: <FaShoppingCart />,
    quantity:1,
  },
  {
    id: 11,
    Company: "IndianGarrageCo",
    Itemname: "footwear",
    url: "/images/MensPageImg/shoes1.png",
    price: 1500,
    cart: <FaShoppingCart />,
    quantity:1,
  },
  {
    id: 12,
    Company: "IndianGarrageCo",
    Itemname: "footwear",
    url: "/images/MensPageImg/shoes3.png",
    price: 1465,
    cart: <FaShoppingCart />,
    quantity:1,
  },
  {
    id: 13,
    Company: "IndianGarrageCo",
    Itemname: "short",
    url: "/images/MensPageImg/short1.png",
    price: 1000,
    cart: <FaShoppingCart />,
    quantity:1,
  },
  {
    id: 14,
    Company: "IndianGarrageCo",
    Itemname: "short",
    url: "/images/MensPageImg/short2.png",
    price: 1600,
    cart: <FaShoppingCart />,
    quantity:1,
  },
  {
    id: 15,
    Company: "IndianGarrageCo",
    Itemname: "short",
    url: "/images/MensPageImg/short3.png",
    price: 1725,
    cart: <FaShoppingCart />,
    quantity:1,
  },
];
